<?php

declare(strict_types=1);

namespace Test\src\Domain\Community;

use App\Domain\Community\CommunityException;
use App\Domain\Community\CommunityFactory;
use Test\AbstractTest;
use WalkWeb\NW\AppException;

class CommunityFactoryTest extends AbstractTest
{
    /**
     * @dataProvider successDataProvider
     * @param array $data
     * @throws AppException
     */
    public function testCommunityFactoryCreateSuccess(array $data): void
    {
        $community = CommunityFactory::create($data);

        self::assertEquals($data['id'], $community->getId());
        self::assertEquals($data['level'], $community->getLevel());
        self::assertEquals($data['name'], $community->getName());
        self::assertEquals($data['slug'], $community->getSlug());
        self::assertEquals($data['description'], $community->getDescription());
        self::assertEquals($data['icon'], $community->getIcon());
        self::assertEquals($data['icon_small'], $community->getIconSmall());
        self::assertEquals($data['head_image'], $community->getHeadImage());
        self::assertEquals($data['followers'], $community->getFollowers());
        self::assertEquals($data['fixed_post_id'], $community->getFixedPostId());
        self::assertEquals($data['menu'], $community->getMenu());
        self::assertEquals($data['owner_id'], $community->getOwnerId());
        self::assertEquals($data['total_post_count'], $community->getTotalPostCount());
        self::assertEquals($data['silver_post_count'], $community->getSilverPostCount());
        self::assertEquals($data['gold_post_count'], $community->getGoldPostCount());
        self::assertEquals($data['diamond_post_count'], $community->getDiamondPostCount());
        self::assertEquals($data['total_comment_count'], $community->getTotalCommentCount());
        self::assertEquals((bool)$data['is_joined'], $community->isJoined());
        self::assertEquals($data['created_at'], $community->getCreatedAt()->format(self::DATE_FORMAT));
        self::assertEquals($data['updated_at'], $community->getUpdatedAt()->format(self::DATE_FORMAT));
    }

    /**
     * @dataProvider failDataProvider
     * @param array $data
     * @param string $error
     */
    public function testCommunityFactoryCreateFail(array $data, string $error): void
    {
        $this->expectException(AppException::class);
        $this->expectExceptionMessage($error);
        CommunityFactory::create($data);
    }

    /**
     * @return array
     */
    public function successDataProvider(): array
    {
        return [
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
            ],
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => null,
                    'menu'                => null,
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => 1,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
            ],
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => null,
                    'menu'                => null,
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => 0,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
            ],
        ];
    }

    /**
     * @return array
     */
    public function failDataProvider(): array
    {
        return [
            // miss id
            [
                [
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_ID,
            ],
            // id invalid type
            [
                [
                    'id'                  => 123,
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_ID,
            ],
            // id invalid uuid
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334xxx',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_ID,
            ],

            // miss level
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_LEVEL,
            ],
            // level invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => null,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_LEVEL,
            ],

            // miss name
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_NAME,
            ],
            // name invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => true,
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_NAME,
            ],

            // miss slug
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_SLUG,
            ],
            // slug invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 5.7,
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_SLUG,
            ],

            // miss description
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_DESCRIPTION,
            ],
            // description invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 2,
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_DESCRIPTION,
            ],

            // miss icon
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_ICON,
            ],
            // icon invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => null,
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_ICON,
            ],

            // miss icon_small
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_ICON_SMALL,
            ],
            // icon_small invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 123,
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_ICON_SMALL,
            ],

            // miss head_image
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_HEAD_IMAGE,
            ],
            // head_image invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => null,
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_HEAD_IMAGE,
            ],

            // miss followers
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_FOLLOWERS,
            ],
            // followers invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => '312',
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_FOLLOWERS,
            ],

            // miss fixed_post_id
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_FIXED_POST_ID,
            ],
            // fixed_post_id invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => true,
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_FIXED_POST_ID,
            ],
            // fixed_post_id invalid uuid
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7baxxx',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_FIXED_POST_ID,
            ],

            // miss menu
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_MENU,
            ],
            // menu invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => 4,
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_MENU,
            ],

            // miss owner_id
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_OWNER_ID,
            ],
            // owner_id invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => 123,
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_OWNER_ID,
            ],
            // owner_id invalid uuid
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3xxx',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_OWNER_ID,
            ],

            // miss total_post_count
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_TOTAL_POST_COUNT,
            ],
            // total_post_count invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => '54',
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_TOTAL_POST_COUNT,
            ],

            // miss silver_post_count
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_SILVER_POST_COUNT,
            ],
            // silver_post_count invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => '13',
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_SILVER_POST_COUNT,
            ],

            // miss gold_post_count
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_GOLD_POST_COUNT,
            ],
            // gold_post_count invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => '5',
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_GOLD_POST_COUNT,
            ],

            // miss diamond_post_count
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_DIAMOND_POST_COUNT,
            ],
            // diamond_post_count invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => '1',
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_DIAMOND_POST_COUNT,
            ],

            // miss total_comment_count
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_TOTAL_COMMENT_COUNT,
            ],
            // total_comment_count invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => null,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_TOTAL_COMMENT_COUNT,
            ],
            // miss is_joined
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 123,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_IS_JOINED,
            ],
            // is_joined invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 123,
                    'is_joined'           => '',
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_IS_JOINED,
            ],

            // miss created_at
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_CREATED_AT,
            ],
            // created_at invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => 321,
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_CREATED_AT,
            ],
            // created_at invalid date
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-99 15:30:00',
                    'updated_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_CREATED_AT,
            ],

            // miss updated_at
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                ],
                CommunityException::INVALID_UPDATED_AT,
            ],

            // updated_at invalid type
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => null,
                ],
                CommunityException::INVALID_UPDATED_AT,
            ],
            // updated_at invalid date
            [
                [
                    'id'                  => '606f332b-4551-4570-842b-498b5d334692',
                    'level'               => 4,
                    'name'                => 'Name Community',
                    'slug'                => 'name-community',
                    'description'         => 'description community',
                    'icon'                => 'icon.png',
                    'icon_small'          => 'icon_small.png',
                    'head_image'          => 'head_image.png',
                    'followers'           => 312,
                    'fixed_post_id'       => '402d565b-94aa-40c9-bdd6-79334f7bafad',
                    'menu'                => '["menu-1", "menu-2", "menu-3"]',
                    'owner_id'            => '4a9820ea-adea-432f-b106-f62ad10b3a03',
                    'total_post_count'    => 54,
                    'silver_post_count'   => 13,
                    'gold_post_count'     => 5,
                    'diamond_post_count'  => 1,
                    'total_comment_count' => 1236,
                    'is_joined'           => null,
                    'created_at'          => '2024-06-21 15:30:00',
                    'updated_at'          => '2024-88-66 15:30:00',
                ],
                CommunityException::INVALID_UPDATED_AT,
            ],
        ];
    }
}
